# Generated by Django 6.0.6 on 2026-06-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0002_remove_pousada_plano_pousada_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaQuarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacidade', models.IntegerField(default=2)),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='pousada.pousada')),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_identificacao', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='pousada.categoriaquarto')),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='pousada.pousada')),
            ],
        ),
    ]
