# Generated by Django 6.0.6 on 2026-06-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0004_pousada_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoBloqueio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos_bloqueio', to='pousada.pousada')),
            ],
        ),
    ]
