# Generated by Django 6.0.6 on 2026-06-11 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0008_alter_pousada_dono_logauditoria'),
        ('reservas', '0009_alter_reserva_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pousada',
            name='usa_checklist_limpeza',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarto',
            name='status_limpeza',
            field=models.CharField(choices=[('sujo', 'Sujo'), ('em_limpeza', 'Em Limpeza'), ('limpo', 'Limpo')], default='limpo', max_length=20),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_itens', to='pousada.pousada')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLimpeza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('sujo', 'Sujo'), ('em_limpeza', 'Em Limpeza'), ('limpo', 'Limpo')], default='sujo', max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_limpeza', to=settings.AUTH_USER_MODEL)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_limpeza', to='pousada.quarto')),
                ('reserva_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_limpeza', to='reservas.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLimpezaConcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('checklist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pousada.checklistitem')),
                ('registro_limpeza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_concluidos', to='pousada.registrolimpeza')),
            ],
        ),
    ]
