# Generated by Django 6.0.6 on 2026-06-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0012_ordemservico_registrolimpeza_ordem_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTuya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.CharField(max_length=100)),
                ('access_secret', models.CharField(max_length=100)),
                ('region', models.CharField(default='western_america', max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fechadura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, unique=True)),
                ('nome_exibicao', models.CharField(max_length=100)),
                ('is_online', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechaduras', to='pousada.quarto')),
            ],
        ),
    ]
