# Generated by Django 6.0.6 on 2026-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0013_configuracaotuya_fechadura'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotuya',
            name='prefixo_pin_padrao',
            field=models.CharField(default='101', max_length=3),
        ),
        migrations.AddField(
            model_name='pousada',
            name='whatsapp_recepcao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
