# Generated by Django 6.0.6 on 2026-06-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0014_configuracaotuya_prefixo_pin_padrao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracaotuya',
            name='prefixo_pin_padrao',
        ),
        migrations.AddField(
            model_name='pousada',
            name='prefixo_pin_padrao',
            field=models.CharField(default='101', max_length=3),
        ),
    ]
