# Generated by Django 6.0.6 on 2026-07-10 20:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0017_configuracaotuya_pousada'),
        ('reservas', '0018_alter_reserva_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaquarto',
            options={'verbose_name': 'Categoria de Quarto', 'verbose_name_plural': 'Categorias de Quartos'},
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'verbose_name': 'Item de Checklist', 'verbose_name_plural': 'Itens de Checklist'},
        ),
        migrations.AlterModelOptions(
            name='configuracaotuya',
            options={'verbose_name': 'Configuração da Tuya', 'verbose_name_plural': 'Configurações da Tuya'},
        ),
        migrations.AlterModelOptions(
            name='fechadura',
            options={'verbose_name': 'Fechadura', 'verbose_name_plural': 'Fechaduras'},
        ),
        migrations.AlterModelOptions(
            name='itemlimpezaconcluido',
            options={'verbose_name': 'Item de Checklist Concluído', 'verbose_name_plural': 'Itens de Checklist Concluídos'},
        ),
        migrations.AlterModelOptions(
            name='logauditoria',
            options={'verbose_name': 'Log de Auditoria', 'verbose_name_plural': 'Logs de Auditorias'},
        ),
        migrations.AlterModelOptions(
            name='metodopagamentoconfig',
            options={'verbose_name': 'Método de Pagamento', 'verbose_name_plural': 'Métodos de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='motivobloqueio',
            options={'verbose_name': 'Motivo de Bloqueio', 'verbose_name_plural': 'Motivos de Bloqueios'},
        ),
        migrations.AlterModelOptions(
            name='ordemservico',
            options={'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterModelOptions(
            name='pousada',
            options={'verbose_name': 'Pousada', 'verbose_name_plural': 'Pousadas'},
        ),
        migrations.AlterModelOptions(
            name='quarto',
            options={'verbose_name': 'Quarto', 'verbose_name_plural': 'Quartos'},
        ),
        migrations.AlterModelOptions(
            name='registrolimpeza',
            options={'verbose_name': 'Registro de Limpeza', 'verbose_name_plural': 'Registros de Limpezas'},
        ),
        migrations.AlterField(
            model_name='categoriaquarto',
            name='capacidade',
            field=models.IntegerField(default=2, verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='categoriaquarto',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoriaquarto',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='categoriaquarto',
            name='valor_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Diária'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='pousada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_itens', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='configuracaotuya',
            name='access_id',
            field=models.CharField(max_length=100, verbose_name='Access ID'),
        ),
        migrations.AlterField(
            model_name='configuracaotuya',
            name='access_secret',
            field=models.CharField(max_length=100, verbose_name='Access Secret'),
        ),
        migrations.AlterField(
            model_name='configuracaotuya',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='configuracaotuya',
            name='pousada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_tuya', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='configuracaotuya',
            name='region',
            field=models.CharField(default='western_america', max_length=50, verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='fechadura',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='fechadura',
            name='device_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Device ID'),
        ),
        migrations.AlterField(
            model_name='fechadura',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='Online'),
        ),
        migrations.AlterField(
            model_name='fechadura',
            name='nome_exibicao',
            field=models.CharField(max_length=100, verbose_name='Nome de Exibição'),
        ),
        migrations.AlterField(
            model_name='fechadura',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechaduras', to='pousada.quarto', verbose_name='Quarto'),
        ),
        migrations.AlterField(
            model_name='itemlimpezaconcluido',
            name='checklist_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pousada.checklistitem', verbose_name='Item de Checklist'),
        ),
        migrations.AlterField(
            model_name='itemlimpezaconcluido',
            name='concluido',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='itemlimpezaconcluido',
            name='registro_limpeza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_concluidos', to='pousada.registrolimpeza', verbose_name='Registro de Limpeza'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(max_length=255, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='alvo_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Alvo'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='pousada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_auditoria', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='metodopagamentoconfig',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='metodopagamentoconfig',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='metodopagamentoconfig',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='motivobloqueio',
            name='cor',
            field=models.CharField(default='#475569', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='motivobloqueio',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='motivobloqueio',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motivos_bloqueio', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='prioridade',
            field=models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=15, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='pousada.quarto', verbose_name='Quarto'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], db_index=True, default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.CharField(choices=[('limpeza', 'Limpeza'), ('encanamento', 'Encanamento'), ('eletrica', 'Elétrica'), ('outros', 'Outros')], db_index=True, max_length=20, verbose_name='Tipo de Serviço'),
        ),
        migrations.AlterField(
            model_name='pousada',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='pousada',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='pousada',
            name='dono',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pousada_owner', to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
        migrations.AlterField(
            model_name='pousada',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='pousada',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pousada',
            name='prefixo_pin_padrao',
            field=models.CharField(default='101', max_length=3, verbose_name='Prefixo PIN Padrão'),
        ),
        migrations.AlterField(
            model_name='pousada',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='pousada',
            name='usa_checklist_limpeza',
            field=models.BooleanField(default=False, verbose_name='Usa Checklist de Limpeza'),
        ),
        migrations.AlterField(
            model_name='pousada',
            name='whatsapp_recepcao',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp da Recepção'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quartos', to='pousada.categoriaquarto', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='nome_identificacao',
            field=models.CharField(max_length=50, verbose_name='Identificação do Quarto'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartos', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='status_limpeza',
            field=models.CharField(choices=[('sujo', 'Sujo'), ('em_limpeza', 'Em Limpeza'), ('limpo', 'Limpo')], db_index=True, default='limpo', max_length=20, verbose_name='Status da Limpeza'),
        ),
        migrations.AlterField(
            model_name='registrolimpeza',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='registrolimpeza',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_limpeza', to=settings.AUTH_USER_MODEL, verbose_name='Funcionário'),
        ),
        migrations.AlterField(
            model_name='registrolimpeza',
            name='ordem_servico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_limpeza', to='pousada.ordemservico', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='registrolimpeza',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_limpeza', to='pousada.quarto', verbose_name='Quarto'),
        ),
        migrations.AlterField(
            model_name='registrolimpeza',
            name='reserva_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_limpeza', to='reservas.reserva', verbose_name='Reserva Relacionada'),
        ),
        migrations.AlterField(
            model_name='registrolimpeza',
            name='status',
            field=models.CharField(choices=[('sujo', 'Sujo'), ('em_limpeza', 'Em Limpeza'), ('limpo', 'Limpo')], db_index=True, default='sujo', max_length=20, verbose_name='Status'),
        ),
    ]
