# Generated by Django 6.0.6 on 2026-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0018_alter_categoriaquarto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pousada',
            name='mensagem_pos_checkin',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem Pós Check-in Online'),
        ),
        migrations.AddField(
            model_name='pousada',
            name='video_pos_checkin',
            field=models.URLField(blank=True, null=True, verbose_name='Vídeo Pós Check-in (YouTube/Vimeo)'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='senha_acesso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Senha de Acesso (Manual)'),
        ),
    ]
