# Generated by Django 6.0.6 on 2026-06-11 17:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pontuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(max_length=100)),
                ('pontos_passaros', models.IntegerField(default=0)),
                ('ovos', models.IntegerField(default=0)),
                ('comida', models.IntegerField(default=0)),
                ('cartas_bonus', models.IntegerField(default=0)),
                ('rodadas', models.IntegerField(default=0)),
                ('pontos_objetivo', models.IntegerField(default=0)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='wingspan.partida')),
            ],
        ),
    ]
