# Generated by Django 6.0.6 on 2026-06-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0005_tag_hospede_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tipo',
            field=models.CharField(choices=[('H', 'Hóspede'), ('R', 'Reserva')], default='H', max_length=10),
        ),
    ]
