# Generated by Django 6.0.6 on 2026-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0006_tag_tipo'),
        ('pousada', '0016_alter_ordemservico_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospede',
            options={'ordering': ['nome_completo']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='nome_completo',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='telefone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('pousada', 'nome')},
        ),
        migrations.AddIndex(
            model_name='hospede',
            index=models.Index(fields=['pousada', 'nome_completo'], name='hospedes_ho_pousada_7a2ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='hospede',
            index=models.Index(fields=['pousada', 'cpf'], name='hospedes_ho_pousada_70cf99_idx'),
        ),
    ]
