# Generated by Django 6.0.6 on 2026-07-10 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0007_alter_hospede_options_alter_tag_options_and_more'),
        ('pousada', '0017_configuracaotuya_pousada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospede',
            options={'ordering': ['nome_completo'], 'verbose_name': 'Hóspede', 'verbose_name_plural': 'Hóspedes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['nome'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='hospede',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='dados_extras',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados Extras'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='endereco_completo',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='nacionalidade',
            field=models.CharField(default='Brasileira', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='nome_completo',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospedes', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hospedes.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='telefone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('PAS', 'Passaporte')], default='CPF', max_length=50, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cor',
            field=models.CharField(default='#3b82f6', max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tipo',
            field=models.CharField(choices=[('H', 'Hóspede'), ('R', 'Reserva')], default='H', max_length=10, verbose_name='Tipo'),
        ),
    ]
