# Generated by Django 6.0.6 on 2026-07-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0008_alter_hospede_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospede',
            name='nacionalidade',
            field=models.CharField(blank=True, default='Brasileira', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('RG', 'RG'), ('PAS', 'Passaporte')], default='CPF', max_length=50, verbose_name='Tipo de Documento'),
        ),
    ]
