# Generated by Django 6.0.6 on 2026-06-10 13:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_remove_reserva_origem_imediata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checkin_concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='meio_transporte',
            field=models.CharField(blank=True, choices=[('aviao', 'Avião'), ('automovel', 'Automóvel'), ('onibus', 'Ônibus'), ('trem', 'Trem'), ('embarcacao', 'Embarcação'), ('outro', 'Outro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='proximo_destino',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='token_checkin',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='ultima_procedencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='motivo_viagem',
            field=models.CharField(blank=True, choices=[('lazer', 'Lazer'), ('negocios', 'Negócios'), ('congresso', 'Congresso/Convenção'), ('parentes', 'Parentes/Amigos'), ('estudos', 'Estudos'), ('saude', 'Saúde'), ('compras', 'Compras'), ('outro', 'Outro')], max_length=50, null=True),
        ),
    ]
