# Generated by Django 6.0.6 on 2026-06-10 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_reserva_checkin_concluido_reserva_meio_transporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='token_checkin',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
