# Generated by Django 6.0.6 on 2026-06-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_token_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fnrh_exportado',
            field=models.BooleanField(default=False),
        ),
    ]
