# Generated by Django 6.0.6 on 2026-06-10 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0006_tag_tipo'),
        ('pousada', '0005_motivobloqueio'),
        ('reservas', '0006_reserva_fnrh_exportado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='is_bloqueio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_bloqueio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pousada.motivobloqueio'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hospedes.tag'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hospedes.hospede'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
