# Generated by Django 6.0.6 on 2026-06-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_alter_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='senha_fechadura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
