# Generated by Django 6.0.6 on 2026-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0011_reserva_token_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='checkin_online_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede_cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
