# Generated by Django 6.0.6 on 2026-06-11 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_reserva_checkin_online_realizado_reserva_hospede_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaFNRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=50)),
                ('cpf_passaporte', models.CharField(max_length=50)),
                ('documento_identidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(default='Brasil', max_length=50)),
                ('placa_veiculo', models.CharField(blank=True, max_length=10, null=True)),
                ('motivo_viagem', models.CharField(choices=[('lazer', 'Lazer'), ('negocios', 'Negócios'), ('outro', 'Outro')], default='lazer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_fnrh', to='reservas.reserva')),
            ],
        ),
    ]
