# Generated by Django 6.0.6 on 2026-06-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0014_remove_fichafnrh_created_at_fichafnrh_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='token_checkin',
        ),
    ]
