# Generated by Django 6.0.6 on 2026-06-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_templatemensagem_logdisparomensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemensagem',
            name='gatilho',
            field=models.CharField(choices=[('criacao_reserva', 'Criação da Reserva'), ('confirmacao_reserva', 'Confirmação da Reserva'), ('antes_checkin', 'Antes do Check-in'), ('depois_checkout', 'Depois do Check-out')], max_length=55),
        ),
    ]
