# Generated by Django 6.0.6 on 2026-06-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pousada', '0006_motivobloqueio_cor'),
        ('reservas', '0008_grupo_acompanhante_reserva_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sinal', 'Sinal'), ('saldo_final', 'Saldo Final'), ('consumo', 'Consumo')], default='saldo_final', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('credito', 'Crédito'), ('debito', 'Débito'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('estornado', 'Estornado')], default='pendente', max_length=20)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pousada.pousada')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='reservas.reserva')),
            ],
        ),
    ]
