# Generated by Django 6.0.6 on 2026-06-15 13:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
        ('pousada', '0016_alter_ordemservico_status_and_more'),
        ('reservas', '0015_remove_token_checkin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_vencimento']},
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['pousada', 'status'], name='financeiro__pousada_44649e_idx'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['reserva', 'status'], name='financeiro__reserva_2fa4ee_idx'),
        ),
    ]
