# Generated by Django 6.0.6 on 2026-07-10 20:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_pagamento_options_alter_pagamento_valor_and_more'),
        ('pousada', '0017_configuracaotuya_pousada'),
        ('reservas', '0018_alter_reserva_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-data_vencimento'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('pix', 'Pix'), ('credito', 'Crédito'), ('debito', 'Débito'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência')], max_length=20, null=True, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='reservas.reserva', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('estornado', 'Estornado')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('sinal', 'Sinal'), ('saldo_final', 'Saldo Final'), ('consumo', 'Consumo')], default='saldo_final', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor'),
        ),
    ]
