# Generated by Django 6.0.6 on 2026-06-11 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_saas', '0002_nivelacesso_clientesaas_nivel_acesso'),
        ('pousada', '0008_alter_pousada_dono_logauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientesaas',
            name='pousada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='pousada.pousada'),
        ),
    ]
