# Generated by Django 6.0.6 on 2026-07-10 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_saas', '0004_nivelacesso_pode_acessar_governanca'),
        ('pousada', '0017_configuracaotuya_pousada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientesaas',
            options={'verbose_name': 'Cliente SaaS', 'verbose_name_plural': 'Clientes SaaS'},
        ),
        migrations.AlterModelOptions(
            name='nivelacesso',
            options={'verbose_name': 'Nível de Acesso', 'verbose_name_plural': 'Níveis de Acesso'},
        ),
        migrations.AlterField(
            model_name='clientesaas',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='clientesaas',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Expiração'),
        ),
        migrations.AlterField(
            model_name='clientesaas',
            name='nivel_acesso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='admin_saas.nivelacesso', verbose_name='Nível de Acesso'),
        ),
        migrations.AlterField(
            model_name='clientesaas',
            name='plano_ativo',
            field=models.BooleanField(default=True, verbose_name='Plano Ativo'),
        ),
        migrations.AlterField(
            model_name='clientesaas',
            name='pousada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='clientesaas',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_saas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='nivelacesso',
            name='nome',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='nivelacesso',
            name='pode_acessar_configuracoes',
            field=models.BooleanField(default=True, verbose_name='Acesso a Configurações'),
        ),
        migrations.AlterField(
            model_name='nivelacesso',
            name='pode_acessar_crm',
            field=models.BooleanField(default=True, verbose_name='Acesso a CRM'),
        ),
        migrations.AlterField(
            model_name='nivelacesso',
            name='pode_acessar_financeiro',
            field=models.BooleanField(default=True, verbose_name='Acesso ao Financeiro'),
        ),
        migrations.AlterField(
            model_name='nivelacesso',
            name='pode_acessar_governanca',
            field=models.BooleanField(default=True, verbose_name='Acesso a Governança'),
        ),
        migrations.AlterField(
            model_name='nivelacesso',
            name='pode_acessar_reservas',
            field=models.BooleanField(default=True, verbose_name='Acesso a Reservas'),
        ),
    ]
