# Generated by Django 6.0.6 on 2026-07-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_saas', '0005_alter_clientesaas_options_alter_nivelacesso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacesso',
            name='pode_apenas_bloquear_mapa',
            field=models.BooleanField(default=False, verbose_name='Apenas Bloqueio de Mapa'),
        ),
    ]
