# Generated by Django 6.0.6 on 2026-06-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospede',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='hospede',
            name='email',
        ),
        migrations.AddField(
            model_name='hospede',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='notas',
            field=models.TextField(blank=True, help_text="Ex: 'Gente boa', 'Prefere quarto no térreo'..."),
        ),
        migrations.AddField(
            model_name='hospede',
            name='tipo_viagem',
            field=models.CharField(choices=[('turismo', 'Turismo'), ('negocio', 'Negócio')], default='turismo', max_length=20),
        ),
    ]
