# Generated by Django 6.0.6 on 2026-06-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0002_remove_hospede_data_nascimento_remove_hospede_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospede',
            old_name='endereco',
            new_name='endereco_completo',
        ),
        migrations.RemoveField(
            model_name='hospede',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='hospede',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='hospede',
            name='tipo_viagem',
        ),
        migrations.AddField(
            model_name='hospede',
            name='dados_extras',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='hospede',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='nacionalidade',
            field=models.CharField(default='Brasileiro(a)', max_length=100),
        ),
        migrations.AddField(
            model_name='hospede',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='tipo_documento',
            field=models.CharField(choices=[('CPF', 'CPF'), ('RG', 'RG'), ('PAS', 'Passaporte')], default='CPF', max_length=50),
        ),
    ]
