# Generated by Django 6.0.6 on 2026-06-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0003_rename_endereco_hospede_endereco_completo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospede',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
