# Generated by Django 6.0.6 on 2026-06-10 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0004_hospede_cep_hospede_cidade_hospede_cpf_and_more'),
        ('pousada', '0004_pousada_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(default='#3b82f6', max_length=7)),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='pousada.pousada')),
            ],
        ),
        migrations.AddField(
            model_name='hospede',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hospedes.tag'),
        ),
    ]
