# Generated by Django 6.0.6 on 2026-06-09 20:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pousada',
            name='plano',
        ),
        migrations.AddField(
            model_name='pousada',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pousada',
            name='dono',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pousada', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pousada',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
