# Generated by Django 6.0.6 on 2026-06-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0003_categoriaquarto_quarto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pousada',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
