# Generated by Django 6.0.6 on 2026-06-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0005_motivobloqueio'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivobloqueio',
            name='cor',
            field=models.CharField(default='#475569', max_length=7),
        ),
    ]
