# Generated by Django 6.0.6 on 2026-06-10 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0006_motivobloqueio_cor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPagamentoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pagamento', to='pousada.pousada')),
            ],
        ),
    ]
