# Generated by Django 6.0.6 on 2026-06-11 17:05

from django.db import migrations


def set_quartos_limpos(apps, schema_editor):
    Quarto = apps.get_model('pousada', 'Quarto')
    # Set all existing quartos to 'limpo'
    Quarto.objects.update(status_limpeza='limpo')

class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0009_pousada_usa_checklist_limpeza_quarto_status_limpeza_and_more'),
    ]

    operations = [
        migrations.RunPython(set_quartos_limpos),
    ]

