# Generated by Django 6.0.6 on 2026-06-11 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0010_auto_20260611_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='pousada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_itens', to='pousada.pousada'),
        ),
    ]
