# Generated by Django 6.0.6 on 2026-06-11 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0011_checklistitem_ativo_alter_checklistitem_pousada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('limpeza', 'Limpeza'), ('encanamento', 'Encanamento'), ('eletrica', 'Elétrica'), ('outros', 'Outros')], max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], default='media', max_length=15)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_criadas', to=settings.AUTH_USER_MODEL)),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='pousada.pousada')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='pousada.quarto')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_atribuidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='registrolimpeza',
            name='ordem_servico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_limpeza', to='pousada.ordemservico'),
        ),
    ]
