# Generated by Django 6.0.6 on 2026-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0015_remove_configuracaotuya_prefixo_pin_padrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], db_index=True, default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.CharField(choices=[('limpeza', 'Limpeza'), ('encanamento', 'Encanamento'), ('eletrica', 'Elétrica'), ('outros', 'Outros')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='status_limpeza',
            field=models.CharField(choices=[('sujo', 'Sujo'), ('em_limpeza', 'Em Limpeza'), ('limpo', 'Limpo')], db_index=True, default='limpo', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrolimpeza',
            name='status',
            field=models.CharField(choices=[('sujo', 'Sujo'), ('em_limpeza', 'Em Limpeza'), ('limpo', 'Limpo')], db_index=True, default='sujo', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='categoriaquarto',
            unique_together={('pousada', 'nome')},
        ),
    ]
