# Generated by Django 6.0.6 on 2026-07-10 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0016_alter_ordemservico_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotuya',
            name='pousada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_tuya', to='pousada.pousada'),
        ),
    ]
