# Generated by Django 6.0.6 on 2026-07-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0019_pousada_mensagem_pos_checkin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalOrigem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Canal')),
                ('cor', models.CharField(default='#6b7280', max_length=20, verbose_name='Cor da Badge')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canais_origem', to='pousada.pousada', verbose_name='Pousada')),
            ],
            options={
                'verbose_name': 'Canal de Origem',
                'verbose_name_plural': 'Canais de Origem',
                'ordering': ['nome'],
            },
        ),
    ]
