# Generated by Django 6.0.6 on 2026-06-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_viagem',
            field=models.CharField(choices=[('lazer', 'Lazer'), ('negocios', 'Negócios'), ('eventos', 'Eventos')], default='lazer', max_length=50),
        ),
        migrations.AddField(
            model_name='reserva',
            name='origem_imediata',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='proximo_destino',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
