# Generated by Django 6.0.6 on 2026-06-09 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0003_categoriaquarto_quarto'),
        ('reservas', '0002_remove_reserva_observacoes_reserva_motivo_viagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='origem_imediata',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='proximo_destino',
        ),
        migrations.AddField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='pousada.quarto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='motivo_viagem',
            field=models.CharField(choices=[('lazer', 'Lazer'), ('negocios', 'Negócios')], default='lazer', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada')], default='pendente', max_length=20),
        ),
    ]
