# Generated by Django 6.0.6 on 2026-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_grupo_acompanhante_reserva_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
