# Generated by Django 6.0.6 on 2026-06-11 18:29

import uuid
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    Reserva = apps.get_model('reservas', 'Reserva')
    for row in Reserva.objects.all():
        row.token_acesso = uuid.uuid4()
        row.save(update_fields=['token_acesso'])


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_reserva_senha_fechadura'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='token_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(gen_uuid, elidable=True),
        migrations.AlterField(
            model_name='reserva',
            name='token_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
