# Generated by Django 6.0.6 on 2026-06-11 22:39

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_fichafnrh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichafnrh',
            name='created_at',
        ),
        migrations.AddField(
            model_name='fichafnrh',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='bairro',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='cep',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='cidade',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='data_nascimento',
            field=models.DateField(default=datetime.date(2026, 6, 11)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='documento_identidade',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='estado',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='logradouro',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='motivo_viagem',
            field=models.CharField(choices=[('lazer', 'Lazer'), ('negocios', 'Negócios'), ('outro', 'Outros')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='nacionalidade',
            field=models.CharField(default='Brasileira', max_length=100),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='numero',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='pais',
            field=models.CharField(default='Brasil', max_length=100),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='telefone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
