# Generated by Django 6.0.6 on 2026-06-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0016_alter_ordemservico_status_and_more'),
        ('reservas', '0015_remove_token_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('gatilho', models.CharField(choices=[('criacao_reserva', 'Criação da Reserva'), ('antes_checkin', 'Antes do Check-in'), ('depois_checkout', 'Depois do Check-out')], max_length=55)),
                ('dias_offset', models.IntegerField(default=0)),
                ('assunto', models.CharField(blank=True, max_length=255, null=True)),
                ('corpo_mensagem', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
                ('pousada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_mensagem', to='pousada.pousada')),
            ],
        ),
        migrations.CreateModel(
            name='LogDisparoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_disparo', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('pendente_whatsapp', 'Pendente WhatsApp')], max_length=30)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_disparo', to='reservas.reserva')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_disparo', to='reservas.templatemensagem')),
            ],
        ),
    ]
