# Generated by Django 6.0.6 on 2026-07-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0017_alter_templatemensagem_gatilho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('sinal', 'Sinal'), ('confirmada', 'Confirmada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
    ]
