# Generated by Django 6.0.6 on 2026-07-10 20:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospedes', '0008_alter_hospede_options_alter_tag_options_and_more'),
        ('pousada', '0018_alter_categoriaquarto_options_and_more'),
        ('reservas', '0018_alter_reserva_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanhante',
            options={'verbose_name': 'Acompanhante', 'verbose_name_plural': 'Acompanhantes'},
        ),
        migrations.AlterModelOptions(
            name='fichafnrh',
            options={'verbose_name': 'Ficha FNRH', 'verbose_name_plural': 'Fichas FNRH'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'verbose_name': 'Grupo de Reserva', 'verbose_name_plural': 'Grupos de Reservas'},
        ),
        migrations.AlterModelOptions(
            name='logdisparomensagem',
            options={'verbose_name': 'Log de Disparo de Mensagem', 'verbose_name_plural': 'Logs de Disparos de Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='templatemensagem',
            options={'verbose_name': 'Template de Mensagem', 'verbose_name_plural': 'Templates de Mensagens'},
        ),
        migrations.AlterField(
            model_name='acompanhante',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='acompanhante',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='acompanhante',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='reservas.reserva', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='cep',
            field=models.CharField(max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='cpf_passaporte',
            field=models.CharField(max_length=50, verbose_name='CPF/Passaporte'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='documento_identidade',
            field=models.CharField(max_length=50, verbose_name='Documento de Identidade'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='logradouro',
            field=models.CharField(max_length=255, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='motivo_viagem',
            field=models.CharField(choices=[('lazer', 'Lazer'), ('negocios', 'Negócios'), ('outro', 'Outros')], max_length=50, verbose_name='Motivo da Viagem'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='nacionalidade',
            field=models.CharField(default='Brasileira', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='pais',
            field=models.CharField(default='Brasil', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_fnrh', to='reservas.reserva', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='fichafnrh',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='logdisparomensagem',
            name='data_disparo',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Disparo'),
        ),
        migrations.AlterField(
            model_name='logdisparomensagem',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_disparo', to='reservas.reserva', verbose_name='Reserva'),
        ),
        migrations.AlterField(
            model_name='logdisparomensagem',
            name='status',
            field=models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('pendente_whatsapp', 'Pendente WhatsApp')], max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='logdisparomensagem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_disparo', to='reservas.templatemensagem', verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkin_concluido',
            field=models.BooleanField(default=False, verbose_name='Check-in Concluído'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkin_online_realizado',
            field=models.BooleanField(default=False, verbose_name='Check-in Online Realizado'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_checkin',
            field=models.DateField(verbose_name='Data de Check-in'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_checkout',
            field=models.DateField(verbose_name='Data de Check-out'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fnrh_exportado',
            field=models.BooleanField(default=False, verbose_name='FNRH Exportada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='reservas.grupo', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='hospedes.hospede', verbose_name='Hóspede'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hospede_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Hóspede'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='is_bloqueio',
            field=models.BooleanField(default=False, verbose_name='É Bloqueio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='meio_transporte',
            field=models.CharField(blank=True, choices=[('aviao', 'Avião'), ('automovel', 'Automóvel'), ('onibus', 'Ônibus'), ('trem', 'Trem'), ('embarcacao', 'Embarcação'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Meio de Transporte'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='motivo_bloqueio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pousada.motivobloqueio', verbose_name='Motivo de Bloqueio'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='motivo_viagem',
            field=models.CharField(blank=True, choices=[('lazer', 'Lazer'), ('negocios', 'Negócios'), ('congresso', 'Congresso/Convenção'), ('parentes', 'Parentes/Amigos'), ('estudos', 'Estudos'), ('saude', 'Saúde'), ('compras', 'Compras'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Motivo da Viagem'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='placa_veiculo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pousada.pousada', verbose_name='Pousada'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='proximo_destino',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Próximo Destino'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='pousada.quarto', verbose_name='Quarto'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='senha_fechadura',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Senha da Fechadura'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('sinal', 'Sinal'), ('confirmada', 'Confirmada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tags',
            field=models.ManyToManyField(blank=True, to='hospedes.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='token_acesso',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de Acesso'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='ultima_procedencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Última Procedência'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='assunto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='canal',
            field=models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='corpo_mensagem',
            field=models.TextField(verbose_name='Corpo da Mensagem'),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='dias_offset',
            field=models.IntegerField(default=0, verbose_name='Dias de Offset'),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='gatilho',
            field=models.CharField(choices=[('criacao_reserva', 'Criação da Reserva'), ('confirmacao_reserva', 'Confirmação da Reserva'), ('antes_checkin', 'Antes do Check-in'), ('depois_checkout', 'Depois do Check-out')], max_length=55, verbose_name='Gatilho'),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='templatemensagem',
            name='pousada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_mensagem', to='pousada.pousada', verbose_name='Pousada'),
        ),
    ]
