# Generated by Django 6.0.6 on 2026-07-24 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pousada', '0020_canalorigem'),
        ('reservas', '0019_alter_acompanhante_options_alter_fichafnrh_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='canal_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='pousada.canalorigem', verbose_name='Canal de Origem'),
        ),
    ]
