# Generated by Django 6.0.6 on 2026-07-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_reserva_canal_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='pre_checkin_enviado',
            field=models.BooleanField(default=False, verbose_name='Link de Pré-checkin Enviado'),
        ),
    ]
