# Generated by Django 6.0.6 on 2026-06-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_saas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('pode_acessar_reservas', models.BooleanField(default=True)),
                ('pode_acessar_crm', models.BooleanField(default=True)),
                ('pode_acessar_financeiro', models.BooleanField(default=True)),
                ('pode_acessar_configuracoes', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientesaas',
            name='nivel_acesso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='admin_saas.nivelacesso'),
        ),
    ]
