# Generated by Django 6.0.6 on 2026-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_saas', '0003_clientesaas_pousada'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivelacesso',
            name='pode_acessar_governanca',
            field=models.BooleanField(default=True),
        ),
    ]
