name: Deploy AuraSaaS to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 2.25.164.139
          username: wilian
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /var/www/SaaSAura
            git pull origin main
            ./venv/bin/pip install -r requirements.txt
            ./venv/bin/python manage.py migrate
            ./venv/bin/python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
